/*
 * This source file was generated by the Gradle 'init' task
 */
package dev.somalley.book;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class Main {
    static Book philo = new Book("Phänomenologie des Geistes", 1807, "Georg Wilhelm Friedrich Hegel", 701);
    @Test void philoIsBig() {
        assertTrue(philo.isBig(), "Phenomenology of spirit has >700 pages and should be considered big");
    }
    @Test void philoMatchesByAuthor() {
        assertTrue(philo.matches("Hegel"), "A book by Hegel should be matched");
    }
    @Test void philoNotMatchedByWrongAuthor() {
        assertFalse(philo.matches("Mayakovskiy"), "This book was not written by Mayakovskiy, so it shouldn't have matched");
    }
    @Test void philoMatchesByTitle() {
        assertTrue(philo.matches("Geistes"), "A book should be matched by its title");
    }
    @Test void philoNoCheaperThan250() {
        assertTrue(philo.estimatePrice() >= 250, "No book can be cheaper than 250");
    }
}
