/*
 * This source file was generated by the Gradle 'init' task
 */
package dev.somalley.book;

public class Book {
    String title;
    int releaseYear;
    Author author;
    int pages;

    public Book(String title,
            int releaseYear,
            Author author,
            int pages) {
        this.title = title;
        this.releaseYear = releaseYear;
        this.author = author;
        this.pages = pages;
    }

    // magic constants start
    static final int BIG_PAGES = 501;
    static final int PRICE_PER_PAGE = 3;
    static final int PRICE_FLOOR = 250;
    // magic constants end

    public boolean isBig() {
        return this.pages >= BIG_PAGES;
    }

    public boolean matches(String word) {
        return this.title.contains(word) || this.author.matches(word);
    }

    public int estimatePrice() {
        return Math.max(
                (int)(this.pages * PRICE_PER_PAGE *
                Math.sqrt(this.author.getRating())),
                PRICE_FLOOR);
    }

}
