/*
 * This source file was generated by the Gradle 'init' task
 */
package dev.somalley.book;

public class Book {
    String title;
    int releaseYear;
    String author;
    int pages;

    public Book(String title,
            int releaseYear,
            String author,
            int pages) {
        this.title = title;
        this.releaseYear = releaseYear;
        this.author = author;
        this.pages = pages;
    }

    // magic constants start
    static final int BIG_PAGES = 501;
    static final int PRICE_PER_PAGE = 3;
    static final int PRICE_FLOOR = 250;
    // magic constants end

    public boolean isBig() {
        return this.pages >= BIG_PAGES;
    }

    /**
     * method checks if <i>word</i> appears in either <i>title</i>
     * or <i>author</i>
     * @param word the word or expression to be searched for. note that
     * it shouldn't contain dollar sign as it is used as a separator.
     * */
    public boolean matches(String word) {
        return (this.title + "$" + this.author).contains(word);
    }

    public int estimatePrice() {
        return Math.max(this.pages * PRICE_PER_PAGE, PRICE_FLOOR);
    }

}
